//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.10.05 at 10:58:10 AM IST
//

package org.hl7.v3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * The BooleanNonNull type is used where a Boolean cannot have a null value. A Boolean value can be
 * either true or false.
 *
 * <p>Java class for BN complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="BN">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:v3}ANYNonNull">
 *       &lt;attribute name="value" type="{urn:hl7-org:v3}bn" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BN")
public class BN extends ANYNonNull {

  @XmlAttribute(name = "value")
  protected Boolean value;

  /**
   * Gets the value of the value property.
   *
   * @return possible object is {@link Boolean }
   */
  public Boolean isValue() {
    return value;
  }

  /**
   * Sets the value of the value property.
   *
   * @param value allowed object is {@link Boolean }
   */
  public void setValue(Boolean value) {
    this.value = value;
  }
}
