//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.10.05 at 10:58:10 AM IST
//

package org.hl7.v3;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for BXIT_IVL_PQ complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="BXIT_IVL_PQ">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:v3}IVL_PQ">
 *       &lt;attribute name="qty" type="{urn:hl7-org:v3}int" default="1" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BXIT_IVL_PQ")
public class BXITIVLPQ extends IVLPQ {

  @XmlAttribute(name = "qty")
  protected BigInteger qty;

  /**
   * Gets the value of the qty property.
   *
   * @return possible object is {@link BigInteger }
   */
  public BigInteger getQty() {
    if (qty == null) {
      return new BigInteger("1");
    } else {
      return qty;
    }
  }

  /**
   * Sets the value of the qty property.
   *
   * @param value allowed object is {@link BigInteger }
   */
  public void setQty(BigInteger value) {
    this.qty = value;
  }
}
