//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.10.05 at 10:58:10 AM IST
//

package org.hl7.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for POCD_MT000040.AuthoringDevice complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="POCD_MT000040.AuthoringDevice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="realmCode" type="{urn:hl7-org:v3}CS" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="typeId" type="{urn:hl7-org:v3}POCD_MT000040.InfrastructureRoot.typeId" minOccurs="0"/>
 *         &lt;element name="templateId" type="{urn:hl7-org:v3}II" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="code" type="{urn:hl7-org:v3}CE" minOccurs="0"/>
 *         &lt;element name="manufacturerModelName" type="{urn:hl7-org:v3}SC" minOccurs="0"/>
 *         &lt;element name="softwareName" type="{urn:hl7-org:v3}SC" minOccurs="0"/>
 *         &lt;element name="asMaintainedEntity" type="{urn:hl7-org:v3}POCD_MT000040.MaintainedEntity" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="nullFlavor" type="{urn:hl7-org:v3}NullFlavor" />
 *       &lt;attribute name="classCode" type="{urn:hl7-org:v3}EntityClassDevice" fixed="DEV" />
 *       &lt;attribute name="determinerCode" type="{urn:hl7-org:v3}EntityDeterminer" fixed="INSTANCE" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "POCD_MT000040.AuthoringDevice",
    propOrder = {
      "realmCode",
      "typeId",
      "templateId",
      "code",
      "manufacturerModelName",
      "softwareName",
      "asMaintainedEntity"
    })
public class POCDMT000040AuthoringDevice {

  protected List<CS> realmCode;
  protected POCDMT000040InfrastructureRootTypeId typeId;
  protected List<II> templateId;
  protected CE code;
  protected SC manufacturerModelName;
  protected SC softwareName;
  protected List<POCDMT000040MaintainedEntity> asMaintainedEntity;

  @XmlAttribute(name = "nullFlavor")
  protected List<String> nullFlavor;

  @XmlAttribute(name = "classCode")
  protected EntityClassDevice classCode;

  @XmlAttribute(name = "determinerCode")
  protected String determinerCode;

  /**
   * Gets the value of the realmCode property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the realmCode property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getRealmCode().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link CS }
   */
  public List<CS> getRealmCode() {
    if (realmCode == null) {
      realmCode = new ArrayList<CS>();
    }
    return this.realmCode;
  }

  /**
   * Gets the value of the typeId property.
   *
   * @return possible object is {@link POCDMT000040InfrastructureRootTypeId }
   */
  public POCDMT000040InfrastructureRootTypeId getTypeId() {
    return typeId;
  }

  /**
   * Sets the value of the typeId property.
   *
   * @param value allowed object is {@link POCDMT000040InfrastructureRootTypeId }
   */
  public void setTypeId(POCDMT000040InfrastructureRootTypeId value) {
    this.typeId = value;
  }

  /**
   * Gets the value of the templateId property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the templateId property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getTemplateId().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link II }
   */
  public List<II> getTemplateId() {
    if (templateId == null) {
      templateId = new ArrayList<II>();
    }
    return this.templateId;
  }

  /**
   * Gets the value of the code property.
   *
   * @return possible object is {@link CE }
   */
  public CE getCode() {
    return code;
  }

  /**
   * Sets the value of the code property.
   *
   * @param value allowed object is {@link CE }
   */
  public void setCode(CE value) {
    this.code = value;
  }

  /**
   * Gets the value of the manufacturerModelName property.
   *
   * @return possible object is {@link SC }
   */
  public SC getManufacturerModelName() {
    return manufacturerModelName;
  }

  /**
   * Sets the value of the manufacturerModelName property.
   *
   * @param value allowed object is {@link SC }
   */
  public void setManufacturerModelName(SC value) {
    this.manufacturerModelName = value;
  }

  /**
   * Gets the value of the softwareName property.
   *
   * @return possible object is {@link SC }
   */
  public SC getSoftwareName() {
    return softwareName;
  }

  /**
   * Sets the value of the softwareName property.
   *
   * @param value allowed object is {@link SC }
   */
  public void setSoftwareName(SC value) {
    this.softwareName = value;
  }

  /**
   * Gets the value of the asMaintainedEntity property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the asMaintainedEntity property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getAsMaintainedEntity().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link POCDMT000040MaintainedEntity
   * }
   */
  public List<POCDMT000040MaintainedEntity> getAsMaintainedEntity() {
    if (asMaintainedEntity == null) {
      asMaintainedEntity = new ArrayList<POCDMT000040MaintainedEntity>();
    }
    return this.asMaintainedEntity;
  }

  /**
   * Gets the value of the nullFlavor property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the nullFlavor property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getNullFlavor().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link String }
   */
  public List<String> getNullFlavor() {
    if (nullFlavor == null) {
      nullFlavor = new ArrayList<String>();
    }
    return this.nullFlavor;
  }

  /**
   * Gets the value of the classCode property.
   *
   * @return possible object is {@link EntityClassDevice }
   */
  public EntityClassDevice getClassCode() {
    if (classCode == null) {
      return EntityClassDevice.DEV;
    } else {
      return classCode;
    }
  }

  /**
   * Sets the value of the classCode property.
   *
   * @param value allowed object is {@link EntityClassDevice }
   */
  public void setClassCode(EntityClassDevice value) {
    this.classCode = value;
  }

  /**
   * Gets the value of the determinerCode property.
   *
   * @return possible object is {@link String }
   */
  public String getDeterminerCode() {
    if (determinerCode == null) {
      return "INSTANCE";
    } else {
      return determinerCode;
    }
  }

  /**
   * Sets the value of the determinerCode property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDeterminerCode(String value) {
    this.determinerCode = value;
  }
}
