//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.10.05 at 10:58:10 AM IST
//

package org.hl7.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for POCD_MT000040.AssignedAuthor complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="POCD_MT000040.AssignedAuthor">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="realmCode" type="{urn:hl7-org:v3}CS" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="typeId" type="{urn:hl7-org:v3}POCD_MT000040.InfrastructureRoot.typeId" minOccurs="0"/>
 *         &lt;element name="templateId" type="{urn:hl7-org:v3}II" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="id" type="{urn:hl7-org:v3}II" maxOccurs="unbounded"/>
 *         &lt;element name="code" type="{urn:hl7-org:v3}CE" minOccurs="0"/>
 *         &lt;element name="addr" type="{urn:hl7-org:v3}AD" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="telecom" type="{urn:hl7-org:v3}TEL" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="assignedPerson" type="{urn:hl7-org:v3}POCD_MT000040.Person" minOccurs="0"/>
 *           &lt;element name="assignedAuthoringDevice" type="{urn:hl7-org:v3}POCD_MT000040.AuthoringDevice" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;element name="representedOrganization" type="{urn:hl7-org:v3}POCD_MT000040.Organization" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="nullFlavor" type="{urn:hl7-org:v3}NullFlavor" />
 *       &lt;attribute name="classCode" type="{urn:hl7-org:v3}RoleClassAssignedEntity" fixed="ASSIGNED" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "POCD_MT000040.AssignedAuthor",
    propOrder = {
      "realmCode",
      "typeId",
      "templateId",
      "id",
      "code",
      "addr",
      "telecom",
      "assignedPerson",
      "assignedAuthoringDevice",
      "representedOrganization"
    })
public class POCDMT000040AssignedAuthor {

  protected List<CS> realmCode;
  protected POCDMT000040InfrastructureRootTypeId typeId;
  protected List<II> templateId;

  @XmlElement(required = true)
  protected List<II> id;

  protected CE code;
  protected List<AD> addr;
  protected List<TEL> telecom;
  protected POCDMT000040Person assignedPerson;
  protected POCDMT000040AuthoringDevice assignedAuthoringDevice;
  protected POCDMT000040Organization representedOrganization;

  @XmlAttribute(name = "nullFlavor")
  protected List<String> nullFlavor;

  @XmlAttribute(name = "classCode")
  protected String classCode;

  /**
   * Gets the value of the realmCode property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the realmCode property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getRealmCode().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link CS }
   */
  public List<CS> getRealmCode() {
    if (realmCode == null) {
      realmCode = new ArrayList<CS>();
    }
    return this.realmCode;
  }

  /**
   * Gets the value of the typeId property.
   *
   * @return possible object is {@link POCDMT000040InfrastructureRootTypeId }
   */
  public POCDMT000040InfrastructureRootTypeId getTypeId() {
    return typeId;
  }

  /**
   * Sets the value of the typeId property.
   *
   * @param value allowed object is {@link POCDMT000040InfrastructureRootTypeId }
   */
  public void setTypeId(POCDMT000040InfrastructureRootTypeId value) {
    this.typeId = value;
  }

  /**
   * Gets the value of the templateId property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the templateId property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getTemplateId().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link II }
   */
  public List<II> getTemplateId() {
    if (templateId == null) {
      templateId = new ArrayList<II>();
    }
    return this.templateId;
  }

  /**
   * Gets the value of the id property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the id property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getId().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link II }
   */
  public List<II> getId() {
    if (id == null) {
      id = new ArrayList<II>();
    }
    return this.id;
  }

  /**
   * Gets the value of the code property.
   *
   * @return possible object is {@link CE }
   */
  public CE getCode() {
    return code;
  }

  /**
   * Sets the value of the code property.
   *
   * @param value allowed object is {@link CE }
   */
  public void setCode(CE value) {
    this.code = value;
  }

  /**
   * Gets the value of the addr property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the addr property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getAddr().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link AD }
   */
  public List<AD> getAddr() {
    if (addr == null) {
      addr = new ArrayList<AD>();
    }
    return this.addr;
  }

  /**
   * Gets the value of the telecom property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the telecom property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getTelecom().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link TEL }
   */
  public List<TEL> getTelecom() {
    if (telecom == null) {
      telecom = new ArrayList<TEL>();
    }
    return this.telecom;
  }

  /**
   * Gets the value of the assignedPerson property.
   *
   * @return possible object is {@link POCDMT000040Person }
   */
  public POCDMT000040Person getAssignedPerson() {
    return assignedPerson;
  }

  /**
   * Sets the value of the assignedPerson property.
   *
   * @param value allowed object is {@link POCDMT000040Person }
   */
  public void setAssignedPerson(POCDMT000040Person value) {
    this.assignedPerson = value;
  }

  /**
   * Gets the value of the assignedAuthoringDevice property.
   *
   * @return possible object is {@link POCDMT000040AuthoringDevice }
   */
  public POCDMT000040AuthoringDevice getAssignedAuthoringDevice() {
    return assignedAuthoringDevice;
  }

  /**
   * Sets the value of the assignedAuthoringDevice property.
   *
   * @param value allowed object is {@link POCDMT000040AuthoringDevice }
   */
  public void setAssignedAuthoringDevice(POCDMT000040AuthoringDevice value) {
    this.assignedAuthoringDevice = value;
  }

  /**
   * Gets the value of the representedOrganization property.
   *
   * @return possible object is {@link POCDMT000040Organization }
   */
  public POCDMT000040Organization getRepresentedOrganization() {
    return representedOrganization;
  }

  /**
   * Sets the value of the representedOrganization property.
   *
   * @param value allowed object is {@link POCDMT000040Organization }
   */
  public void setRepresentedOrganization(POCDMT000040Organization value) {
    this.representedOrganization = value;
  }

  /**
   * Gets the value of the nullFlavor property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the nullFlavor property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getNullFlavor().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link String }
   */
  public List<String> getNullFlavor() {
    if (nullFlavor == null) {
      nullFlavor = new ArrayList<String>();
    }
    return this.nullFlavor;
  }

  /**
   * Gets the value of the classCode property.
   *
   * @return possible object is {@link String }
   */
  public String getClassCode() {
    if (classCode == null) {
      return "ASSIGNED";
    } else {
      return classCode;
    }
  }

  /**
   * Sets the value of the classCode property.
   *
   * @param value allowed object is {@link String }
   */
  public void setClassCode(String value) {
    this.classCode = value;
  }
}
