//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.10.05 at 10:58:10 AM IST
//

package org.hl7.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for POCD_MT000040.ParentDocument complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="POCD_MT000040.ParentDocument">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="realmCode" type="{urn:hl7-org:v3}CS" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="typeId" type="{urn:hl7-org:v3}POCD_MT000040.InfrastructureRoot.typeId" minOccurs="0"/>
 *         &lt;element name="templateId" type="{urn:hl7-org:v3}II" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="id" type="{urn:hl7-org:v3}II" maxOccurs="unbounded"/>
 *         &lt;element name="code" type="{urn:hl7-org:v3}CD" minOccurs="0"/>
 *         &lt;element name="text" type="{urn:hl7-org:v3}ED" minOccurs="0"/>
 *         &lt;element name="setId" type="{urn:hl7-org:v3}II" minOccurs="0"/>
 *         &lt;element name="versionNumber" type="{urn:hl7-org:v3}INT" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="nullFlavor" type="{urn:hl7-org:v3}NullFlavor" />
 *       &lt;attribute name="classCode" type="{urn:hl7-org:v3}ActClinicalDocument" fixed="DOCCLIN" />
 *       &lt;attribute name="moodCode" type="{urn:hl7-org:v3}ActMood" fixed="EVN" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "POCD_MT000040.ParentDocument",
    propOrder = {
      "realmCode",
      "typeId",
      "templateId",
      "id",
      "code",
      "text",
      "setId",
      "versionNumber"
    })
public class POCDMT000040ParentDocument {

  protected List<CS> realmCode;
  protected POCDMT000040InfrastructureRootTypeId typeId;
  protected List<II> templateId;

  @XmlElement(required = true)
  protected List<II> id;

  protected CD code;
  protected ED text;
  protected II setId;
  protected INT versionNumber;

  @XmlAttribute(name = "nullFlavor")
  protected List<String> nullFlavor;

  @XmlAttribute(name = "classCode")
  protected ActClinicalDocument classCode;

  @XmlAttribute(name = "moodCode")
  protected List<String> moodCode;

  /**
   * Gets the value of the realmCode property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the realmCode property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getRealmCode().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link CS }
   */
  public List<CS> getRealmCode() {
    if (realmCode == null) {
      realmCode = new ArrayList<CS>();
    }
    return this.realmCode;
  }

  /**
   * Gets the value of the typeId property.
   *
   * @return possible object is {@link POCDMT000040InfrastructureRootTypeId }
   */
  public POCDMT000040InfrastructureRootTypeId getTypeId() {
    return typeId;
  }

  /**
   * Sets the value of the typeId property.
   *
   * @param value allowed object is {@link POCDMT000040InfrastructureRootTypeId }
   */
  public void setTypeId(POCDMT000040InfrastructureRootTypeId value) {
    this.typeId = value;
  }

  /**
   * Gets the value of the templateId property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the templateId property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getTemplateId().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link II }
   */
  public List<II> getTemplateId() {
    if (templateId == null) {
      templateId = new ArrayList<II>();
    }
    return this.templateId;
  }

  /**
   * Gets the value of the id property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the id property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getId().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link II }
   */
  public List<II> getId() {
    if (id == null) {
      id = new ArrayList<II>();
    }
    return this.id;
  }

  /**
   * Gets the value of the code property.
   *
   * @return possible object is {@link CD }
   */
  public CD getCode() {
    return code;
  }

  /**
   * Sets the value of the code property.
   *
   * @param value allowed object is {@link CD }
   */
  public void setCode(CD value) {
    this.code = value;
  }

  /**
   * Gets the value of the text property.
   *
   * @return possible object is {@link ED }
   */
  public ED getText() {
    return text;
  }

  /**
   * Sets the value of the text property.
   *
   * @param value allowed object is {@link ED }
   */
  public void setText(ED value) {
    this.text = value;
  }

  /**
   * Gets the value of the setId property.
   *
   * @return possible object is {@link II }
   */
  public II getSetId() {
    return setId;
  }

  /**
   * Sets the value of the setId property.
   *
   * @param value allowed object is {@link II }
   */
  public void setSetId(II value) {
    this.setId = value;
  }

  /**
   * Gets the value of the versionNumber property.
   *
   * @return possible object is {@link INT }
   */
  public INT getVersionNumber() {
    return versionNumber;
  }

  /**
   * Sets the value of the versionNumber property.
   *
   * @param value allowed object is {@link INT }
   */
  public void setVersionNumber(INT value) {
    this.versionNumber = value;
  }

  /**
   * Gets the value of the nullFlavor property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the nullFlavor property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getNullFlavor().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link String }
   */
  public List<String> getNullFlavor() {
    if (nullFlavor == null) {
      nullFlavor = new ArrayList<String>();
    }
    return this.nullFlavor;
  }

  /**
   * Gets the value of the classCode property.
   *
   * @return possible object is {@link ActClinicalDocument }
   */
  public ActClinicalDocument getClassCode() {
    if (classCode == null) {
      return ActClinicalDocument.DOCCLIN;
    } else {
      return classCode;
    }
  }

  /**
   * Sets the value of the classCode property.
   *
   * @param value allowed object is {@link ActClinicalDocument }
   */
  public void setClassCode(ActClinicalDocument value) {
    this.classCode = value;
  }

  /**
   * Gets the value of the moodCode property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the moodCode property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getMoodCode().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link String }
   */
  public List<String> getMoodCode() {
    if (moodCode == null) {
      moodCode = new ArrayList<String>();
    }
    return this.moodCode;
  }
}
