//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.10.05 at 10:58:10 AM IST
//

package org.hl7.v3;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for RTO_MO_PQ complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RTO_MO_PQ">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:hl7-org:v3}QTY">
 *       &lt;sequence>
 *         &lt;element name="numerator" type="{urn:hl7-org:v3}MO"/>
 *         &lt;element name="denominator" type="{urn:hl7-org:v3}PQ"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "RTO_MO_PQ",
    propOrder = {"numerator", "denominator"})
public class RTOMOPQ extends QTY {

  @XmlElement(required = true)
  protected MO numerator;

  @XmlElement(required = true)
  protected PQ denominator;

  /**
   * Gets the value of the numerator property.
   *
   * @return possible object is {@link MO }
   */
  public MO getNumerator() {
    return numerator;
  }

  /**
   * Sets the value of the numerator property.
   *
   * @param value allowed object is {@link MO }
   */
  public void setNumerator(MO value) {
    this.numerator = value;
  }

  /**
   * Gets the value of the denominator property.
   *
   * @return possible object is {@link PQ }
   */
  public PQ getDenominator() {
    return denominator;
  }

  /**
   * Sets the value of the denominator property.
   *
   * @param value allowed object is {@link PQ }
   */
  public void setDenominator(PQ value) {
    this.denominator = value;
  }
}
