//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.10.05 at 10:58:10 AM IST
//

package org.hl7.v3;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * Java class for StrucDoc.Colgroup complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="StrucDoc.Colgroup">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="col" type="{urn:hl7-org:v3}StrucDoc.Col"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" type="{http://www.w3.org/2001/XMLSchema}ID" />
 *       &lt;attribute name="language" type="{http://www.w3.org/2001/XMLSchema}NMTOKEN" />
 *       &lt;attribute name="styleCode" type="{http://www.w3.org/2001/XMLSchema}NMTOKENS" />
 *       &lt;attribute name="span" type="{http://www.w3.org/2001/XMLSchema}string" default="1" />
 *       &lt;attribute name="width" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="align">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="left"/>
 *             &lt;enumeration value="center"/>
 *             &lt;enumeration value="right"/>
 *             &lt;enumeration value="justify"/>
 *             &lt;enumeration value="char"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="char" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="charoff" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="valign">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="top"/>
 *             &lt;enumeration value="middle"/>
 *             &lt;enumeration value="bottom"/>
 *             &lt;enumeration value="baseline"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "StrucDoc.Colgroup",
    propOrder = {"col"})
public class StrucDocColgroup {

  protected List<StrucDocCol> col;

  @XmlAttribute(name = "ID")
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  @XmlID
  @XmlSchemaType(name = "ID")
  protected String id;

  @XmlAttribute(name = "language")
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  @XmlSchemaType(name = "NMTOKEN")
  protected String language;

  @XmlAttribute(name = "styleCode")
  @XmlSchemaType(name = "NMTOKENS")
  protected List<String> styleCode;

  @XmlAttribute(name = "span")
  protected String span;

  @XmlAttribute(name = "width")
  protected String width;

  @XmlAttribute(name = "align")
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  protected String align;

  @XmlAttribute(name = "char")
  protected String _char;

  @XmlAttribute(name = "charoff")
  protected String charoff;

  @XmlAttribute(name = "valign")
  @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
  protected String valign;

  /**
   * Gets the value of the col property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the col property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getCol().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link StrucDocCol }
   */
  public List<StrucDocCol> getCol() {
    if (col == null) {
      col = new ArrayList<StrucDocCol>();
    }
    return this.col;
  }

  /**
   * Gets the value of the id property.
   *
   * @return possible object is {@link String }
   */
  public String getID() {
    return id;
  }

  /**
   * Sets the value of the id property.
   *
   * @param value allowed object is {@link String }
   */
  public void setID(String value) {
    this.id = value;
  }

  /**
   * Gets the value of the language property.
   *
   * @return possible object is {@link String }
   */
  public String getLanguage() {
    return language;
  }

  /**
   * Sets the value of the language property.
   *
   * @param value allowed object is {@link String }
   */
  public void setLanguage(String value) {
    this.language = value;
  }

  /**
   * Gets the value of the styleCode property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the styleCode property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getStyleCode().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link String }
   */
  public List<String> getStyleCode() {
    if (styleCode == null) {
      styleCode = new ArrayList<String>();
    }
    return this.styleCode;
  }

  /**
   * Gets the value of the span property.
   *
   * @return possible object is {@link String }
   */
  public String getSpan() {
    if (span == null) {
      return "1";
    } else {
      return span;
    }
  }

  /**
   * Sets the value of the span property.
   *
   * @param value allowed object is {@link String }
   */
  public void setSpan(String value) {
    this.span = value;
  }

  /**
   * Gets the value of the width property.
   *
   * @return possible object is {@link String }
   */
  public String getWidth() {
    return width;
  }

  /**
   * Sets the value of the width property.
   *
   * @param value allowed object is {@link String }
   */
  public void setWidth(String value) {
    this.width = value;
  }

  /**
   * Gets the value of the align property.
   *
   * @return possible object is {@link String }
   */
  public String getAlign() {
    return align;
  }

  /**
   * Sets the value of the align property.
   *
   * @param value allowed object is {@link String }
   */
  public void setAlign(String value) {
    this.align = value;
  }

  /**
   * Gets the value of the char property.
   *
   * @return possible object is {@link String }
   */
  public String getChar() {
    return _char;
  }

  /**
   * Sets the value of the char property.
   *
   * @param value allowed object is {@link String }
   */
  public void setChar(String value) {
    this._char = value;
  }

  /**
   * Gets the value of the charoff property.
   *
   * @return possible object is {@link String }
   */
  public String getCharoff() {
    return charoff;
  }

  /**
   * Sets the value of the charoff property.
   *
   * @param value allowed object is {@link String }
   */
  public void setCharoff(String value) {
    this.charoff = value;
  }

  /**
   * Gets the value of the valign property.
   *
   * @return possible object is {@link String }
   */
  public String getValign() {
    return valign;
  }

  /**
   * Sets the value of the valign property.
   *
   * @param value allowed object is {@link String }
   */
  public void setValign(String value) {
    this.valign = value;
  }
}
