//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.10.05 at 10:58:10 AM IST
//

package org.hl7.v3;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * Java class for URLScheme.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <p>
 *
 * <pre>
 * &lt;simpleType name="URLScheme">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="fax"/>
 *     &lt;enumeration value="file"/>
 *     &lt;enumeration value="ftp"/>
 *     &lt;enumeration value="http"/>
 *     &lt;enumeration value="mailto"/>
 *     &lt;enumeration value="mllp"/>
 *     &lt;enumeration value="modem"/>
 *     &lt;enumeration value="nfs"/>
 *     &lt;enumeration value="tel"/>
 *     &lt;enumeration value="telnet"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "URLScheme")
@XmlEnum
public enum URLScheme {
  @XmlEnumValue("fax")
  FAX("fax"),
  @XmlEnumValue("file")
  FILE("file"),
  @XmlEnumValue("ftp")
  FTP("ftp"),
  @XmlEnumValue("http")
  HTTP("http"),
  @XmlEnumValue("mailto")
  MAILTO("mailto"),
  @XmlEnumValue("mllp")
  MLLP("mllp"),
  @XmlEnumValue("modem")
  MODEM("modem"),
  @XmlEnumValue("nfs")
  NFS("nfs"),
  @XmlEnumValue("tel")
  TEL("tel"),
  @XmlEnumValue("telnet")
  TELNET("telnet");
  private final String value;

  URLScheme(String v) {
    value = v;
  }

  public String value() {
    return value;
  }

  public static URLScheme fromValue(String v) {
    for (URLScheme c : URLScheme.values()) {
      if (c.value.equals(v)) {
        return c;
      }
    }
    throw new IllegalArgumentException(v);
  }
}
