CREATE TABLE IF NOT EXISTS public.client_details
(
    id INT PRIMARY KEY,
    access_token varchar(255),
    aa_id varchar(255),
    clientId varchar(255) not null,
    clientSecret varchar(255),
    debug_fhir_query_and_eicr bit NOT NULL DEFAULT FALSE,
    direct_host varchar(255),
    direct_pwd varchar(255),
    direct_recipient_address varchar(255),
    direct_user varchar(255),
    encounter_end_time varchar(255),
    encounter_start_time varchar(255),
    fhir_server_base_url varchar(255) not null,
    imap_port varchar(255),
    imap_url varchar(255),
    rrprocessing_both bit NOT NULL DEFAULT FALSE,
    is_covid19 bit NOT NULL DEFAULT FALSE,
    rrprocessing_createdocref bit NOT NULL DEFAULT FALSE,
    is_direct bit NOT NULL DEFAULT FALSE,
    is_emergent_reporting_enabled bit NOT NULL DEFAULT FALSE,
    is_full_ecr bit NOT NULL DEFAULT TRUE,
    rrprocessing_invokerestapi bit NOT NULL DEFAULT FALSE,
    is_multi_tenant_system_launch bit DEFAULT FALSE,
    is_provider_launch bit NOT NULL DEFAULT FALSE,
    is_restapi bit NOT NULL DEFAULT FALSE,
    is_system_launch bit NOT NULL DEFAULT TRUE,
    is_user_account_launch integer,
    is_xdr bit NOT NULL DEFAULT FALSE,
    last_updated_ts timestamp NOT NULL,
    require_aud bit NOT NULL DEFAULT FALSE,
    rest_api_url varchar(255),
    rr_doc_ref_mime_type varchar(255),
    rr_rest_api_url varchar(255),
    scopes varchar(255) not null,
    smtp_port varchar(255),
    smtp_url varchar(255),
    token_expiry integer DEFAULT 0,
    token_expiry_date timestamp,
    token_url varchar(255),
    xdr_recipient_address varchar(255),
    UNIQUE (fhir_server_base_url)
);