DO
$$
DECLARE
    old_table TEXT := 'healthcare_setting';
    new_table TEXT := 'healthcare_setting_v2';
    row_count_old BIGINT;
    row_count_new BIGINT;
    missing_cols INT;
    col_list TEXT := '';
    select_list TEXT := '';
	missing_in_new TEXT;
    col RECORD;
BEGIN
    ------------------------------------------------------------------
    -- 1. Ensure old table exists
    ------------------------------------------------------------------
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = old_table
    ) THEN
        RAISE EXCEPTION 'Old table "%" does not exist. Migration aborted.', old_table;
    END IF;

    ------------------------------------------------------------------
    -- 2. Create new table (WITHOUT constraints or indexes)
    ------------------------------------------------------------------
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = new_table
    ) THEN
        RAISE NOTICE 'Creating new table "%"...', new_table;

        EXECUTE format($fmt$
            CREATE TABLE %I (
                id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                clientId VARCHAR(8000) NOT NULL,
                clientSecret VARCHAR(8000),
                fhir_server_base_url VARCHAR(8000) NOT NULL,
                fhir_version VARCHAR(255),
                token_url VARCHAR(8000),
                scopes TEXT NOT NULL,
                default_provider_id VARCHAR(8000),
                is_direct INTEGER NOT NULL DEFAULT 0,
                is_xdr INTEGER NOT NULL DEFAULT 0,
                is_restapi INTEGER NOT NULL DEFAULT 0,
                is_fhir INTEGER NOT NULL DEFAULT 0,
                direct_host VARCHAR(8000),
                direct_user VARCHAR(255),
                direct_pwd VARCHAR(255),
                smtp_port VARCHAR(255),
                smtp_url VARCHAR(255),
                imap_port VARCHAR(255),
                imap_url VARCHAR(255),
                pop_port VARCHAR(255),
                pop_url VARCHAR(255),
                direct_recipient_address VARCHAR(255),
                smtp_tls_version VARCHAR(255),
                xdr_recipient_address VARCHAR(255),
                rest_api_url VARCHAR(255),
                create_doc_ref_response INTEGER DEFAULT 0,
                doc_ref_mime_type VARCHAR(255),
                response_rest_api_url VARCHAR(255),
                aa_id VARCHAR(255),
                encounter_start_time VARCHAR(255),
                encounter_end_time VARCHAR(255),
                kars_active TEXT,
                auth_type VARCHAR(8000) NOT NULL,
                ehr_access_token TEXT,
                ehr_access_token_expiry_duration INTEGER,
                token_expiry_date TIMESTAMP,
                require_aud INTEGER NOT NULL DEFAULT 0,
                ehr_supports_subscriptions INTEGER DEFAULT 0,
                trusted_third_party VARCHAR(8000),
                pha_url VARCHAR(8000),
                org_name VARCHAR(8000),
                org_id_system VARCHAR(8000),
                org_id VARCHAR(8000),
                off_hours_start INTEGER,
                off_hours_start_min INTEGER,
                off_hours_end INTEGER,
                off_hours_end_min INTEGER,
                off_hours_timezone VARCHAR(8000),
                off_hours_enabled INTEGER DEFAULT 1,
                username VARCHAR(8000),
                password VARCHAR(8000),
                backend_auth_key_alias VARCHAR(8000),
                backend_auth_alg VARCHAR(8000),
                backend_auth_kid VARCHAR(8000),
                debug_enabled INTEGER DEFAULT 1,
                direct_endpoint_cert_alias VARCHAR(8000),
                smtp_auth_enabled INTEGER DEFAULT 0,
                smtp_ssl_enabled INTEGER DEFAULT 0,
                last_updated_ts TIMESTAMP NOT NULL DEFAULT now()
            );
        $fmt$, new_table);

        RAISE NOTICE 'Table "%" created successfully (without constraints).', new_table;
    ELSE
        RAISE NOTICE 'Table "%" already exists. Proceeding with validation...', new_table;
    END IF;

    ------------------------------------------------------------------
    -- 3. Verify column compatibility between old and new tables
    ------------------------------------------------------------------
    SELECT COUNT(*) INTO missing_cols
    FROM (
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = new_table
        EXCEPT
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = old_table
    ) diff;

 -- Collect missing column names into a comma-separated list
    SELECT COALESCE(string_agg(column_name, ', '), 'None')
    INTO missing_in_new
    FROM (
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = new_table
        EXCEPT
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = old_table
    ) diff;



    IF missing_cols > 0 THEN
       RAISE EXCEPTION 'Column mismatch detected in : % column(s) missing in "%": % please add misssing in order to migrate ',
            missing_cols, old_table, missing_in_new;
    ELSE
        RAISE NOTICE 'All columns from "%" exist in "%".', old_table, new_table;
    END IF;

    ------------------------------------------------------------------
    -- 4. Data migration
    ------------------------------------------------------------------
    EXECUTE format('SELECT COUNT(*) FROM %I', old_table) INTO row_count_old;

    IF row_count_old = 0 THEN
        RAISE NOTICE 'No rows found in "%". Skipping migration.', old_table;
        RETURN;
    END IF;

    RAISE NOTICE 'Found % rows in "%". Proceeding with migration...',
        row_count_old, old_table;

    ------------------------------------------------------------------
    -- 5. Build column list dynamically for data copy
    ------------------------------------------------------------------
    FOR col IN
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = old_table
        ORDER BY ordinal_position
    LOOP
        IF EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = new_table
              AND column_name = col.column_name
        ) THEN
            col_list := col_list || format('%I, ', col.column_name);
            select_list := select_list || format('%I, ', col.column_name);
        END IF;
    END LOOP;

    col_list := regexp_replace(col_list, ',\s*$', '');
    select_list := regexp_replace(select_list, ',\s*$', '');

    ------------------------------------------------------------------
    -- 6. Copy data
    ------------------------------------------------------------------
    RAISE NOTICE 'Inserting data into "%" ...', new_table;
    EXECUTE format('INSERT INTO %I (%s) SELECT %s FROM %I;',
                   new_table, col_list, select_list, old_table);

    EXECUTE format('SELECT COUNT(*) FROM %I', new_table) INTO row_count_new;

    IF row_count_new != row_count_old THEN
        RAISE EXCEPTION 'Row count mismatch. Old=% New=%',
            row_count_old, row_count_new;
    ELSE
        RAISE NOTICE 'Data migration successful. % rows copied from "%" to "%".',
            row_count_new, old_table, new_table;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'Error during migration: %', SQLERRM;
        RAISE NOTICE 'Rolling back transaction.';
        RAISE;
END;
$$;



 
 