
DO
$$
DECLARE
    old_table TEXT := 'kar_info';
    new_table TEXT := 'kar_info_v2';
    row_count_old BIGINT;
    row_count_new BIGINT;
    missing_cols INT;
    missing_in_new TEXT;
    col_list TEXT := '';
    select_list TEXT := '';
    col RECORD;
BEGIN



    ------------------------------------------------------------------
    -- 0. Create new table if old table does NOT exist
    ------------------------------------------------------------------
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = old_table
    ) THEN



        RAISE NOTICE 'Old table "%" does not exist. Creating only new table "%".',
            old_table, new_table;



        -- Create new table if not already present
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = 'public' AND table_name = new_table
        ) THEN



            EXECUTE format($fmt$
                CREATE TABLE %I (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    kar_id VARCHAR(8000) NOT NULL,
                    kar_name VARCHAR(8000) NOT NULL,
                    kar_publisher VARCHAR(8000) NOT NULL,
                    kar_version VARCHAR(8000) NOT NULL,
                    kar_available INTEGER NOT NULL DEFAULT 0,
                    repo_id INTEGER
                );
            $fmt$, new_table);

            EXECUTE format('CREATE INDEX IF NOT EXISTS idx_kar_id_v2 ON %I (kar_id);', new_table);

            RAISE NOTICE 'Table "%" created successfully.', new_table;



        ELSE
            RAISE NOTICE 'Table "%" already exists. No migration needed.', new_table;
        END IF;

        RETURN;
    END IF;

    ------------------------------------------------------------------
    -- 1. Old table exists → ensure new table exists
    ------------------------------------------------------------------
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_schema = 'public' AND table_name = new_table
    ) THEN

        RAISE NOTICE 'Creating new table "%" for migration...', new_table;


        EXECUTE format($fmt$
            CREATE TABLE %I (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                kar_id VARCHAR(8000) NOT NULL,
                kar_name VARCHAR(8000) NOT NULL,
                kar_publisher VARCHAR(8000) NOT NULL,
                kar_version VARCHAR(8000) NOT NULL,
                kar_available INTEGER NOT NULL DEFAULT 0,
                repo_id INTEGER
            );
        $fmt$, new_table);



        EXECUTE format('CREATE INDEX IF NOT EXISTS idx_kar_id_v2 ON %I (kar_id);', new_table);


        RAISE NOTICE 'New table "%" created.', new_table;
    ELSE
        RAISE NOTICE 'New table "%" already exists.', new_table;
    END IF;


    ------------------------------------------------------------------
    -- 2. Verify column compatibility
    ------------------------------------------------------------------
    SELECT COUNT(*) INTO missing_cols
    FROM (
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = new_table
        EXCEPT
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = old_table
    ) diff;


    SELECT COALESCE(string_agg(column_name, ', '), 'None')
    INTO missing_in_new
    FROM (
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = new_table
        EXCEPT
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = old_table
    ) diff;


    IF missing_cols > 0 THEN
        RAISE EXCEPTION 'Column mismatch: % column(s) missing in "%": %',
            missing_cols, old_table, missing_in_new;
    ELSE
        RAISE NOTICE 'Column compatibility OK.';
    END IF;

    ------------------------------------------------------------------
    -- 3. Data migration
    ------------------------------------------------------------------
    EXECUTE format('SELECT COUNT(*) FROM %I;', old_table)
        INTO row_count_old;



    IF row_count_old = 0 THEN
        RAISE NOTICE 'No rows to migrate from "%".', old_table;
        RETURN;
    END IF;



    -- Build column lists dynamically
    FOR col IN
        SELECT column_name
        FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = old_table
        ORDER BY ordinal_position
    LOOP
        IF EXISTS (
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'public'
              AND table_name = new_table
              AND column_name = col.column_name
        ) THEN
            col_list := col_list || format('%I, ', col.column_name);
            select_list := select_list || format('%I, ', col.column_name);
        END IF;
    END LOOP;

    col_list := regexp_replace(col_list, ',\s*$', '');
    select_list := regexp_replace(select_list, ',\s*$', '');

    RAISE NOTICE 'Migrating % rows...', row_count_old;


    EXECUTE format(
        'INSERT INTO %I (%s) SELECT %s FROM %I;',
        new_table, col_list, select_list, old_table
    );


    EXECUTE format('SELECT COUNT(*) FROM %I;', new_table)
        INTO row_count_new;


    IF row_count_new != row_count_old THEN
        RAISE EXCEPTION 'Row count mismatch: old=% new=%',
            row_count_old, row_count_new;
    ELSE
        RAISE NOTICE 'Migration successful: % rows copied.', row_count_new;
    END IF;

EXCEPTION
    WHEN OTHERS THEN
        RAISE NOTICE 'Error: %', SQLERRM;
        RAISE NOTICE 'Rolling back.';
        RAISE;
END;
$$;
