FROM centos:latest
MAINTAINER eCRNow DB

RUN cd /etc/yum.repos.d/
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

ADD docker-scripts/run.sh /bin/run.sh
RUN chmod +x /bin/run.sh

RUN yum update -y

RUN yum install postgresql-server -y

ENV TZ=${TZ:-'America/New_York'}

RUN echo "America/New_York" > /etc/timezone

EXPOSE 5432

CMD ["/bin/run.sh"]
