//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.7
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.10.05 at 10:58:10 AM IST
//

package org.hl7.sdtc;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.hl7.v3.CS;
import org.hl7.v3.II;
import org.hl7.v3.POCDMT000040InfrastructureRootTypeId;
import org.hl7.v3.XDocumentActMood;

/**
 * Java class for ActReference complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ActReference">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="realmCode" type="{urn:hl7-org:v3}CS" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="typeId" type="{urn:hl7-org:v3}POCD_MT000040.InfrastructureRoot.typeId" minOccurs="0"/>
 *         &lt;element name="templateId" type="{urn:hl7-org:v3}II" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="id" type="{urn:hl7-org:v3}II" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="classCode" use="required" type="{urn:hl7-org:v3}ActClass" />
 *       &lt;attribute name="moodCode" use="required" type="{urn:hl7-org:v3}x_DocumentActMood" />
 *       &lt;attribute name="determinerCode" type="{urn:hl7-org:v3}EntityDeterminer" fixed="INSTANCE" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(
    name = "ActReference",
    propOrder = {"realmCode", "typeId", "templateId", "id"})
public class ActReference {

  protected List<CS> realmCode;
  protected POCDMT000040InfrastructureRootTypeId typeId;
  protected List<II> templateId;

  @XmlElement(required = true)
  protected List<II> id;

  @XmlAttribute(name = "classCode", required = true)
  protected List<String> classCode;

  @XmlAttribute(name = "moodCode", required = true)
  protected XDocumentActMood moodCode;

  @XmlAttribute(name = "determinerCode")
  protected String determinerCode;

  /**
   * Gets the value of the realmCode property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the realmCode property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getRealmCode().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link CS }
   */
  public List<CS> getRealmCode() {
    if (realmCode == null) {
      realmCode = new ArrayList<CS>();
    }
    return this.realmCode;
  }

  /**
   * Gets the value of the typeId property.
   *
   * @return possible object is {@link POCDMT000040InfrastructureRootTypeId }
   */
  public POCDMT000040InfrastructureRootTypeId getTypeId() {
    return typeId;
  }

  /**
   * Sets the value of the typeId property.
   *
   * @param value allowed object is {@link POCDMT000040InfrastructureRootTypeId }
   */
  public void setTypeId(POCDMT000040InfrastructureRootTypeId value) {
    this.typeId = value;
  }

  /**
   * Gets the value of the templateId property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the templateId property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getTemplateId().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link II }
   */
  public List<II> getTemplateId() {
    if (templateId == null) {
      templateId = new ArrayList<II>();
    }
    return this.templateId;
  }

  /**
   * Gets the value of the id property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the id property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getId().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link II }
   */
  public List<II> getId() {
    if (id == null) {
      id = new ArrayList<II>();
    }
    return this.id;
  }

  /**
   * Gets the value of the classCode property.
   *
   * <p>This accessor method returns a reference to the live list, not a snapshot. Therefore any
   * modification you make to the returned list will be present inside the JAXB object. This is why
   * there is not a <CODE>set</CODE> method for the classCode property.
   *
   * <p>For example, to add a new item, do as follows:
   *
   * <pre>
   *    getClassCode().add(newItem);
   * </pre>
   *
   * <p>Objects of the following type(s) are allowed in the list {@link String }
   */
  public List<String> getClassCode() {
    if (classCode == null) {
      classCode = new ArrayList<String>();
    }
    return this.classCode;
  }

  /**
   * Gets the value of the moodCode property.
   *
   * @return possible object is {@link XDocumentActMood }
   */
  public XDocumentActMood getMoodCode() {
    return moodCode;
  }

  /**
   * Sets the value of the moodCode property.
   *
   * @param value allowed object is {@link XDocumentActMood }
   */
  public void setMoodCode(XDocumentActMood value) {
    this.moodCode = value;
  }

  /**
   * Gets the value of the determinerCode property.
   *
   * @return possible object is {@link String }
   */
  public String getDeterminerCode() {
    if (determinerCode == null) {
      return "INSTANCE";
    } else {
      return determinerCode;
    }
  }

  /**
   * Sets the value of the determinerCode property.
   *
   * @param value allowed object is {@link String }
   */
  public void setDeterminerCode(String value) {
    this.determinerCode = value;
  }
}
