name: Build Docker Image and Send Email

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  docker-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          IMAGE_TAG=${{ secrets.IMAGE_TAG }}-v${{ github.run_number }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${IMAGE_TAG} -f ./project-directory/Dockerfile .
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_TAG }}

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          from: ${{ secrets.SMTP_USERNAME }}
          subject: "Docker Image Build Successful - ${{ env.IMAGE_TAG }}"
          body: |
            The Docker image has been built and pushed successfully.

            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
            Docker Image: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_TAG }}
          to: ${{ secrets.RECIPIENT_EMAIL }}
          content_type: text/plain    